name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Set execute permissions and list files
      run: |
        chmod +x export.sh
        chmod +x Import.sh

    - name: Install dependencies and deploy Lambda
      run: |
        ./export.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"

    - name: Run Import Script
      run: |
        ./Import.sh 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_1 }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_1 }}
        AWS_DEFAULT_REGION: "us-east-1"
    
    - name: Create GitHub tag on successful import
      if: success()
      run: |       
        # Set the value of $LATEST_MODEL if needed
        LATEST_MODEL="your_value_here"
                
        # Get the commit SHA
        COMMIT_SHA=$(git rev-parse --short HEAD)

        # Create a GitHub tag
        TAG_NAME="Lex-$LATEST_MODEL"
        git tag $TAG_NAME
        git push origin $TAG_NAME $GH_TOKEN
        echo "GitHub tag created: $TAG_NAME"
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
